### ISSUE TITLE
Install script still searching for "solid-dark"

### ISSUE THREAD

**Issue by choopsit** [vinceliuice/Mojave-gtk-theme#185]
Hello

It seems that "solid-dark" versions of the theme are no longer available, but "install.sh"  still tries to deploy these variants:
```
[choops@mrchat /tmp/mojave-gtk]$ sudo ./install.sh 
[sudo] password for choops: 
==> Generating the gtk-light.css...
==> Generating the gnome-shell-light.css...
==> Generating the cinnamon-light.css...
==> Generating the gtk-light.css...
==> Generating the gnome-shell-light.css...
==> Generating the cinnamon-light.css...
==> Generating the gtk-dark.css...
==> Generating the gnome-shell-dark.css...
==> Generating the cinnamon-dark.css...
==> Generating the gtk-dark.css...
==> Generating the gnome-shell-dark.css...
==> Generating the cinnamon-dark.css...
Installing '/usr/share/themes/Mojave-light'...
Installing '/usr/share/themes/Mojave-light-alt'...
Installing '/usr/share/themes/Mojave-light-solid'...
cp: cannot stat '/tmp/mojave-gtk/src/main/gnome-shell/gnome-shell-light-solid.css': No such file or directory
cp: cannot stat '/tmp/mojave-gtk/src/main/gtk-3.0/gtk-dark-solid.css': No such file or directory
cp: cannot stat '/tmp/mojave-gtk/src/main/gtk-3.0/gtk-light-solid.css': No such file or directory
/tmp/mojave-gtk/src/main/gtk-3.0/gtk.gresource.xml: Failed to locate “gtk.css” in any source directory.
cp: cannot stat '/tmp/mojave-gtk/src/main/cinnamon/cinnamon-light-solid.css': No such file or directory
Installing '/usr/share/themes/Mojave-light-solid-alt'...
cp: cannot stat '/tmp/mojave-gtk/src/main/gnome-shell/gnome-shell-light-solid.css': No such file or directory
cp: cannot stat '/tmp/mojave-gtk/src/main/gtk-3.0/gtk-dark-solid.css': No such file or directory
cp: cannot stat '/tmp/mojave-gtk/src/main/gtk-3.0/gtk-light-solid.css': No such file or directory
/tmp/mojave-gtk/src/main/gtk-3.0/gtk.gresource.xml: Failed to locate “gtk.css” in any source directory.
cp: cannot stat '/tmp/mojave-gtk/src/main/cinnamon/cinnamon-light-solid.css': No such file or directory
Installing '/usr/share/themes/Mojave-dark'...
Installing '/usr/share/themes/Mojave-dark-alt'...
Installing '/usr/share/themes/Mojave-dark-solid'...
cp: cannot stat '/tmp/mojave-gtk/src/main/gnome-shell/gnome-shell-dark-solid.css': No such file or directory
cp: cannot stat '/tmp/mojave-gtk/src/main/gtk-3.0/gtk-dark-solid.css': No such file or directory
cp: cannot stat '/tmp/mojave-gtk/src/main/gtk-3.0/gtk-dark-solid.css': No such file or directory
/tmp/mojave-gtk/src/main/gtk-3.0/gtk.gresource.xml: Failed to locate “gtk.css” in any source directory.
cp: cannot stat '/tmp/mojave-gtk/src/main/cinnamon/cinnamon-dark-solid.css': No such file or directory
Installing '/usr/share/themes/Mojave-dark-solid-alt'...
cp: cannot stat '/tmp/mojave-gtk/src/main/gnome-shell/gnome-shell-dark-solid.css': No such file or directory
cp: cannot stat '/tmp/mojave-gtk/src/main/gtk-3.0/gtk-dark-solid.css': No such file or directory
cp: cannot stat '/tmp/mojave-gtk/src/main/gtk-3.0/gtk-dark-solid.css': No such file or directory
/tmp/mojave-gtk/src/main/gtk-3.0/gtk.gresource.xml: Failed to locate “gtk.css” in any source directory.
cp: cannot stat '/tmp/mojave-gtk/src/main/cinnamon/cinnamon-dark-solid.css': No such file or directory

Done.
[choops@mrchat /tmp/mojave-gtk]$ 
```

**Comment by vinceliuice** [comment]
You can try the last update, I think is fixed

**Comment by choopsit** [comment]
Last update of the repo seems to have been done 5 days ago. So, I totally reclone the repo to be sure I had no residual things.
Not really successful... I still have the same problem.

Sorry to just be a sad messenger. I'll go and search a way to help when I can have few minutes

**Comment by vinceliuice** [comment]
I'll check the the sh files, there must be something wrong with it

**Comment by vinceliuice** [comment]
Now it's fixed
